name: Feature Request
description: Suggest an idea for SimpleDisplay.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: A clear description of the problem.

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      placeholder: Any alternative solutions or workarounds?
